### ISSUE TITLE
IlmImf is not correctly linked for Debug configurations

### ISSUE THREAD

**Issue by kutschkem** [conan-community/conan-opencv#4]
IlmImf can't be linked on Windows for multi- or Debug configurations.

        if self.settings.os == "Windows" and not self.options.shared:
            self.cpp_info.libs.extend(["IlmImf"])

should read

        if self.settings.os == "Windows" and not self.options.shared:
            self.cpp_info.libs.extend(["IlmImf%s" % debug])

**Comment by SSE4** [comment]
I think it's no longer actual with updated recipe, as we're using IlmImf from our OpenEXR package now. @kutschkem could you possibly give an another try?

**Comment by kutschkem** [comment]
Well since the offending code is not there anymore I think the issue can be closed. I haven't tried with the current recipe but the OpenEXR package looks like it is adding the d suffix.
